apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  finalizers:
  - application-connector-manager.kyma-project.io/deletion-hook
  labels:
    app.kubernetes.io/instance: application-connector
    app.kubernetes.io/managed-by: application-connector-manager
    app.kubernetes.io/name: application-connector
    app.kubernetes.io/part-of: application-connector-manager
    release: application-connector
  name: kyma-gateway-application-connector
  namespace: kyma-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "gateway.kyma.example.com"
    port:
      name: https-app-connector
      number: 443
      protocol: HTTPS
    tls:
      credentialName: kyma-gateway-certs
      mode: MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  finalizers:
  - application-connector-manager.kyma-project.io/deletion-hook
  labels:
    app: central-application-connectivity-validator
    app.kubernetes.io/instance: application-connector
    app.kubernetes.io/managed-by: application-connector-manager
    app.kubernetes.io/name: central-application-connectivity-validator
    app.kubernetes.io/part-of: application-connector-manager
    release: application-connector
  name: central-application-connectivity-validator
  namespace: kyma-system
spec:
  gateways:
  - kyma-system/kyma-gateway-application-connector
  hosts:
  - "gateway.kyma.example.com"
  http:
  - match:
    - uri:
        regex: ^/[^/]+/v1/metadata(/|/.*)?
    - uri:
        regex: ^/[^/]+/v1/events(/|/.*)?
    - uri:
        regex: ^/[^/]+/v2/events(/|/.*)?
    - uri:
        regex: ^/[^/]+/events(/|/.*)?
    route:
    - destination:
        host: central-application-connectivity-validator
        port:
          number: 8080
