module-name: application-connector-manager
kind: kyma
bdba:
  - europe-docker.pkg.dev/kyma-project/prod/application-connector-manager:1.1.13
  - europe-docker.pkg.dev/kyma-project/prod/application-connector-manager:latest
  - europe-docker.pkg.dev/kyma-project/prod/central-application-connectivity-validator:1.1.13
  - europe-docker.pkg.dev/kyma-project/prod/central-application-connectivity-validator:latest
  - europe-docker.pkg.dev/kyma-project/prod/central-application-gateway:1.1.13
  - europe-docker.pkg.dev/kyma-project/prod/central-application-gateway:latest
  - europe-docker.pkg.dev/kyma-project/prod/compass-runtime-agent:1.1.13
  - europe-docker.pkg.dev/kyma-project/prod/compass-runtime-agent:latest
mend:
  language: golang-mod
  exclude:
    - '**/*_test.go'
checkmarx-one:
  preset: go-default
  exclude:
    - '**/*_test.go'
