module-name: application-connector-manager
kind: kyma
bdba:
  - europe-docker.pkg.dev/kyma-project/prod/application-connector-manager:1.2.0
  - europe-docker.pkg.dev/kyma-project/prod/central-application-connectivity-validator:1.2.0
  - europe-docker.pkg.dev/kyma-project/prod/central-application-gateway:1.2.0
  - europe-docker.pkg.dev/kyma-project/prod/compass-runtime-agent:1.2.0
mend:
  language: golang-mod
  exclude:
    - '**/*_test.go'
checkmarx-one:
  preset: go-default
  exclude:
    - '**/*_test.go'
